name: create branch
on:
 workflow_dispatch 
jobs:
  create_branch_job:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt update 
    - name: git install
      run: sudo apt install git
    - name: global user email
      run: git config --global user.email "zabarishi@gmail.com"
    - name: gloabl user id
      run: git config --global user.name "zabarishi"
    - name: ssh git
       run: ssh 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@github.com:zabarishi/WWWv1.0.git    
      #run: curl -u https://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@github.com/zabarishi/WWWv1.0
      #run: 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@github.com:zabarishi/WWWv1.0.git
    - name: create new branch
      run: git checkout -b www/worktest
